name: Android App APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
<<<<<<< HEAD

=======
      
>>>>>>> b734e48b51156f56ed5de06a3a3f8d9f40f4d60e
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
<<<<<<< HEAD
          cache: "npm"
=======
          cache: 'npm'
>>>>>>> b734e48b51156f56ed5de06a3a3f8d9f40f4d60e

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
<<<<<<< HEAD
          java-version: "17"
          distribution: "temurin"
=======
          java-version: '17'
          distribution: 'temurin'
>>>>>>> b734e48b51156f56ed5de06a3a3f8d9f40f4d60e

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Android app
<<<<<<< HEAD
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/releases/download/homepage-hub.apk
=======
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk
>>>>>>> b734e48b51156f56ed5de06a3a3f8d9f40f4d60e

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
<<<<<<< HEAD
          path: ${{ github.workspace }}/releases/download/homepage-hub.apk
=======
          path: ${{ github.workspace }}/app-release.apk
>>>>>>> b734e48b51156f56ed5de06a3a3f8d9f40f4d60e
